### ISSUE TITLE
cannot import name 'darwin' from 'pyffmpeg.static.bin.darwin'

### ISSUE THREAD

**Issue by slhck** [deuteronomy-works/pyffmpeg#125]
Given the following test file:

```
from pyffmpeg import FFmpeg
```

It fails with:

```
Traceback (most recent call last):
  File "/Users/werner/Documents/Software/pyffmpeg/test.py", line 12, in <module>
    ff = FFmpeg()
  File "/Users/werner/Documents/Software/pyffmpeg/pyffmpeg/__init__.py", line 40, in __init__
    self._ffmpeg_file = Paths().load_ffmpeg_bin()
  File "/Users/werner/Documents/Software/pyffmpeg/pyffmpeg/misc.py", line 50, in load_ffmpeg_bin
    from .static.bin.darwin import darwin
ImportError: cannot import name 'darwin' from 'pyffmpeg.static.bin.darwin' (/Users/werner/Documents/Software/pyffmpeg/pyffmpeg/static/bin/darwin/__init__.py)
```

There is no module `darwin` in the module `darwin`, so I think the import is wrong. This may hold for other OSes as well.

Even if I change the import in `misc.py` to `from .static.bin import darwin`, it errors with:

```
module 'pyffmpeg.static.bin.darwin' has no attribute 'contents'
```

Python 3.8.1 under macOS 10.15.7.

**Comment by slhck** [comment]
It seems you used to have `contents` with a base-64-encoded executable in the individual package files, but not anymore, so I consider this part of the functionality somehow broken?

**Comment by amoh-godwin** [comment]
The problem is due to the fact that the wheel names on PyPI are mostly guesswork. So pip installed the source files instead, that would have worked if you had a previous version installed.

I am sure the new filenames will work well.

**Comment by slhck** [comment]
I am actually working with the source code of this repo, not the PyPI installation. Is that not expected to work?

**Comment by amoh-godwin** [comment]
Yes it is expected to work, but you have to be on the branch `build-darwin` before you can get access to the `darwin.py` file. Sorry though

**Comment by slhck** [comment]
I see … wouldn't it make more sense to have everything be part of one branch? This means master will always be broken, which is a bit confusing.

**Comment by amoh-godwin** [comment]
Its like that because of the build process, we might end up adding everything to the wheel files, that means the wheel will be very big with multiple os version of ffmpeg binaries..
