### ISSUE TITLE
Possible FFmpeg license violation

### ISSUE THREAD

**Issue by slhck** [deuteronomy-works/pyffmpeg#126]
In the README it says:

> The beautiful thing about it is that it comes with its own FFmpeg executable.

Judging from how I interpret this code, it comes with different static binaries of ffmpeg already precompiled. (Despite #125 showing that something does not work.) If this is the case, it is a violation of the FFmpeg LGPL v2.1 license. The license requires you, when you distribute FFmpeg, to not only include the source code, but also the license terms and the used compilation commands.

See [ffmpeg.org/legal.html](https://ffmpeg.org/legal.html) for more information and what can be done to rectify the issue.

**Comment by slhck** [comment]
I just verified, indeed the packages at https://pypi.org/project/pyffmpeg/#files distribute ffmpeg precompiled binaries.

Please modify your repository to make it compliant with the FFmpeg license.

**Comment by amoh-godwin** [comment]
I was going through the license requirements just about 3 days ago. I will do as you say. Thanks

**Comment by amoh-godwin** [comment]
Done. The project uses the prebuilt version of it so I have stated so and also given the links to them. I hope all is well now. @slhck

**Comment by slhck** [comment]
So you are packaging the builds directly? I am not sure if this is fully LGPL-compliant, since you are providing the builds without the source code and the respective build information. If you look at the websites for the builds, these do it correctly. I am not a lawyer so I will leave this caveat here, but using the LGPL-compliant builds is surely better than rolling your own.
