### ISSUE TITLE
Add a logger

### ISSUE THREAD

**Issue by amoh-godwin** [deuteronomy-works/pyffmpeg#136]

**Comment by seesiva** [comment]
File "/home/ec2-user/.local/lib/python2.7/site-packages/pyffmpeg/__init__.py", line 63
    options = f"{self._ffmpeg_file} -loglevel {self.loglevel} "

**Comment by amoh-godwin** [comment]
@seesiva LOL! Not that logger. But something like that logger for pyffmpeg to make finding bugs really easy.
