### ISSUE TITLE
after the upgrade to pyffmpeg-2.2.0.1, the compiled ffmpeg is not found

### ISSUE THREAD

**Issue by opabjumbs** [deuteronomy-works/pyffmpeg#157]
Hello,

It looks like the precompiled ffmpeg executable is not included in the latest build for unix systems (reproduced on Debian & Mac)

This is the output from Jenkins on Debian

content/video_thumb.py:51: in thumb_from_video
    ff.options(f"-i '{video}' -ss {second} -filter:v scale='{wxh}:force_original_aspect_ratio=decrease' -vframes 1 {complete_path_to_thumb}")
../venv/lib/python3.8/site-packages/pyffmpeg/__init__.py:174: in options
    out = Popen(options, shell=False, stdin=PIPE, stdout=PIPE, stderr=PIPE)
/usr/local/lib/python3.8/subprocess.py:858: in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
...

E               FileNotFoundError: [Errno 2] No such file or directory: "/var/lib/jenkins/.pyffmpeg/bin/ffmpeg -y -i '../www/media/upload/68312937d288981ae8b4b1bbc5d7d2ec.mp4' -ss 1.5 -filter:v scale='240:135:force_original_aspect_ratio=decrease' -vframes 1 ../www/media/upload/thumbs/small/f8d7f703fe59b20e48e36b156d591939.mp4.jpg"

Thank you very much for your help!

**Comment by amoh-godwin** [comment]
@opadjumps You are very right. The push was not made to the various branches that handle the build for the various OSes, since we are using a script to handle the creation of releases now.
I have made the push and have incremented the version number so now 2.2.1 comes with the compiled binaries.

Thank you very much

**Comment by opabjumbs** [comment]
Thank you very much. Now the compiled binaries are mostly present (except for Apple M1 processor (not all darwins were created the same :-/ )). However, I'm still getting the same File not found error and it seems that this is due to this change https://github.com/deuteronomy-works/pyffmpeg/commit/354e0e056f68e9e22e1d4d02c7763c66fa59fa17 When I set shell=True locally, everything seems to be running happily again. Would you mind reverting that commit? Thank you!

**Comment by amoh-godwin** [comment]
closing now
