### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by amoh-godwin** [deuteronomy-works/pyffmpeg#172]
Fix typos and grammatical errors in the [How to Contribute](https://github.com/deuteronomy-works/pyffmpeg/wiki/How-to-Contribute) file

**Comment by EnigmaDamn** [comment]
[How-to-Contribute.md](https://github.com/deuteronomy-works/pyffmpeg/files/8171518/How-to-Contribute.md)
Fixed typos

**Comment by amoh-godwin** [comment]
@EnigmaDamn Thank you. But why didn't you make a pull request?
