### ISSUE TITLE
Fix typos in the wiki

### ISSUE THREAD

**Issue by amoh-godwin** [deuteronomy-works/pyffmpeg#174]
Any amount of fixes will be accepted

**Comment by EnigmaDamn** [comment]
Repo's Wiki don't gets forked. So [here's](https://github.com/EnigmaDamn/pyffmpeg-wiki) my edits. Also the pull request doesn't compare wiki of my forked repo.

**Comment by amoh-godwin** [comment]
Hello @EnigmaDamn Thank you for your contributions and sorry about that. Wiki's get forked locally independently. But now I have made changes to the settings of this repo. For your name to be captured for your works, you have to make the changes yourself. I have now allowed the wiki to be editable by Github users.

Please make them yourself.

Thank you again

**Comment by EnigmaDamn** [comment]
Done

**Comment by amoh-godwin** [comment]
@EnigmaDamn Thank you very much
