### ISSUE TITLE
FFprobe `duration` property returns 0

### ISSUE THREAD

**Issue by adhadse** [deuteronomy-works/pyffmpeg#206]
I am using `pyffmeg` using version `2.0.1a1`. I tried to find duration of a music file, which I can play and does has content, but the FFprobe returned it's property `0`. This is reproducible on Google Colab (I have tried it). 

Version `2.0.1` does not show this kind of behavior (on my local installation). I have to use version `2.0.1a1` on colab because of this same [issue](https://github.com/deuteronomy-works/pyffmpeg/issues/91) discussed.

**Comment by amoh-godwin** [comment]
@adhadse I suspect maybe a pip3 install pyffmpeg would have solved the problem. Anyway, since yesterday, I have been trying to get tests to run on CentOS to be able to diagnose the problems.

**Comment by adhadse** [comment]
I haven't really checked this issue anymore, instead I am now using Moviepy to get duration (Which I was using anyway for other purpose across the project).

I'll close this issue as this isn't such a big problem😃.
