### ISSUE TITLE
Getting pyffmpeg to work with pyinstaller

### ISSUE THREAD

**Issue by jwbn** [deuteronomy-works/pyffmpeg#29]
Sorry if this is the wrong place to post. This has been a lifesaver for my project.

I use the library to combine a video file and an audio file into an output file.

I'm using pyinstaller to turn my project into an .exe. I'm using the command ```pyinstaller --onefile --noconsole --name ytdl-helper main.py```, this works well for the GUI and Pytube library and they both are functional when using the exe. However, when I run the exe and it needs to use ffmpeg, I get a fatal error saying it couldn't call "Main". I believe that it can't find the ffmpeg exe. I've tried including the provided ffmpeg.exe in the exe using --add-binary but I still can't get it to work.

Any idea of how I could get it to work? Thanks

**Comment by jwbn** [comment]
Update: Ran the packaged .exe with the command prompt open. FileNotFoundError: No such file or directory: 'C:\\Users\\X\\AppData\\Local\\Temp\\_MEI56962\\pyffmpeg\\.\\static\\bin\\win32\\ffmpeg.exe" - the place where pyinstaller temporarily extracts.

**Comment by jwbn** [comment]
**Fix found**

Found that pyffmpeg was looking for a "pyffmpeg" folder that wasn't being carried over to the .exe. Copied the folder from my site-packages and it works now!

**Comment by jwbn** [comment]
Thought I'd update this issue with how I fixed it specifically in case anyone needs help in the future.

1. Copy ffmpeg.exe from the site-packages/pyffmpeg/static/bin/win32 folder to the same directory as your main python script
2. Run pyinstaller with the following commands ```pyinstaller --onefile --name name --add-binary ffmpeg.exe;pyffmpeg/static/bin/win32 script.py```
3. Test script - should now work properly

**Comment by amoh-godwin** [comment]
@jwbn Thank you so much for caring. But it really should work without you needing to include the exe. Even it is bad to include it that way since it is 60mb which greatly increases the size of your bundled app, the py version is only 12mb. This issue will be checked and fixed.

**Comment by amoh-godwin** [comment]
@jwbn The problem was that pyffmpeg itself wasn't creating folders, that's why. Now it's fixed in version 1.6. It works out of the box with pyinstaller, no need for any additional twerks. Thank you for reporting the problem.

**Comment by jwbn** [comment]
Thanks for the update! Great to hear, I'll rebuild my release.
