### ISSUE TITLE
unpacked ffmpeg file is not executable on darwin

### ISSUE THREAD

**Issue by justvanrossum** [deuteronomy-works/pyffmpeg#33]
...and therefore `subprocess.check_output()` fails.

**Comment by justvanrossum** [comment]
```
Python 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyffmpeg import FFmpeg
>>> ff = FFmpeg()
>>> ff.convert("a.mp4", "b.mp3")
ffmpeg version 3.4.2-tessus Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/just/code/git/drawbot-skia/venv/lib/python3.8/site-packages/pyffmpeg/__init__.py", line 100, in convert
    check_output([
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/just/code/git/drawbot-skia/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg', '-loglevel', 'fatal', '-y', '-i', 'a.mp4', './b.mp3']' returned non-zero exit status 1.
>>> 
```

**Comment by amoh-godwin** [comment]
hello @justvanrossum,
thank you for showing the full log. The log reveals that FFmpeg itself is the one reporting the error. The command we issued is wrong. You can see this in the line that says:

> usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}

Can you please use the fullpath to the `a.mp4` as` /path/to/a.mp4` or `./a.mp4` to see it that helps. 

If it doesn't, then, can you please manually on the terminal, using the path to the ffmpeg most probably at **_/Users/just/code/git/drawbot-skia/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg_** issue this command for me and lets see.

`>>> /Users/just/code/git/drawbot-skia/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg -i a.mp4 b.mp3`

And see if that works.

Thank you in advance

**Comment by amoh-godwin** [comment]
Ok, none of that is the problem. Python 3.8 forces a PEP on subprocess, that is the issue.
Proof of that is the `subprocess.CalledProcessError` errror.

The code on github has been updated and a wheel will be made soon. Thank you for reporting this.

**Comment by justvanrossum** [comment]
Ok, I see that my error message was not the right one. Once the new wheel is up I will try again, thanks!

**Comment by justvanrossum** [comment]
It still doesn't work. Here's a complete session, creating a virtual environment from scratch. You'll see a "permission denied" log message. After I `chmod +x` the executable, it does work, but gives me an ffmpeg error (which is fine with me, at this point I'm only interested in having a working ffmpeg executable around).

```
just$ ls -l
total 48
-rw-r--r--  1 just  staff    219 Oct  2 07:33 pyffmpeg_test.py
-rw-r--r--@ 1 just  staff  16685 Oct  2 07:33 test_input.mp4
just$ cat pyffmpeg_test.py 
import os
from pyffmpeg import FFmpeg

inpath = os.path.abspath("test_input.mp4")
outpath = "test_output.mp3"

assert os.path.exists(inpath)
assert not os.path.exists(outpath)

ff = FFmpeg()
ff.convert(inpath, outpath)
just$ python3 -m venv venv
just$ source venv/bin/activate
(venv) just$ pip install --upgrade pip -q
(venv) just$ pip install pyffmpeg
Collecting pyffmpeg
  Using cached pyffmpeg-1.7.0-cp35.cp36.cp37.cp38.cp39-abi3-macosx_10_6_intel.whl (11.0 MB)
Installing collected packages: pyffmpeg
Successfully installed pyffmpeg-1.7.0
(venv) just$ python pyffmpeg_test.py 
-loglevel: /Users/just/code/git/drawbot-skia/ffmpegtest/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg: Permission denied
Traceback (most recent call last):
  File "pyffmpeg_test.py", line 11, in <module>
    ff.convert(inpath, outpath)
  File "/Users/just/code/git/drawbot-skia/ffmpegtest/venv/lib/python3.8/site-packages/pyffmpeg/__init__.py", line 116, in convert
    check_output([
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/just/code/git/drawbot-skia/ffmpegtest/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg', '-loglevel', 'fatal', '-y', '-i', '/Users/just/code/git/drawbot-skia/ffmpegtest/test_input.mp4', './test_output.mp3']' returned non-zero exit status 126.
(venv) just$ ls -l /Users/just/code/git/drawbot-skia/ffmpegtest/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg
-rw-r--r--  1 just  staff  44076796 Oct  2 07:51 /Users/just/code/git/drawbot-skia/ffmpegtest/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg
(venv) just$ chmod +x /Users/just/code/git/drawbot-skia/ffmpegtest/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg
(venv) just$ python pyffmpeg_test.py 
ffmpeg version 3.4.2-tessus Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
Traceback (most recent call last):
  File "pyffmpeg_test.py", line 11, in <module>
    ff.convert(inpath, outpath)
  File "/Users/just/code/git/drawbot-skia/ffmpegtest/venv/lib/python3.8/site-packages/pyffmpeg/__init__.py", line 116, in convert
    check_output([
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/just/code/git/drawbot-skia/ffmpegtest/venv/lib/python3.8/site-packages/pyffmpeg/./static/bin/darwin/ffmpeg', '-loglevel', 'fatal', '-y', '-i', '/Users/just/code/git/drawbot-skia/ffmpegtest/test_input.mp4', './test_output.mp3']' returned non-zero exit status 1.
(venv) just$ 
```

[testfiles.zip](https://github.com/deuteronomy-works/pyffmpeg/files/5316192/testfiles.zip)

**Comment by justvanrossum** [comment]
Btw. the creation of the file `FFMBIN.PYF` in the current directory is a problem, and not only because it confused the hell out of me while debugging this :).

I think the logic of `load_ffmpeg_bin()` should be:
- create platform path for the binary
- if it exists, return it
- import  platform contents
- decompress and save
- return path

(The saving of the executable at all is a potential problem, too, as depending on how/where pyffmpeg was installed, you may not have write permissions inside the package once you import pyffmpeg.)

**Comment by amoh-godwin** [comment]
I am sure 1.7.1 will solve the problem, it was uploaded just a while ago.
The changes requested for `load_ffmpeg_bin()` is done and will be available in 1.7.2, also today.

However, concerning the problem of the executable and of `FFMBIN.PYF` those should be in `1.8`. Where a .pyffmpeg folder will be created in the user's home directory for both files and all other files.

Thank you

**Comment by justvanrossum** [comment]
To be honest, saving files at all may not be the best approach, even in the home directory.

It is possible to build platform wheels that simply contain the executable, ready to use, without the need to unpack and save. I'm not sure how it is done, but I do know https://pypi.org/project/opentype-sanitizer/#files uses this approach. Similar to pyffmpeg, this project wraps prebuilt binaries in a handy Python package.

**Comment by justvanrossum** [comment]
> without the need to unpack and save

I mean at run time, as opposed to install time.

**Comment by amoh-godwin** [comment]
That is possible. But considering the fact that bundle builders or package freezers like pyInstaller won't include it by default and might require a hook or even the developer to manually include the executable, that is something we should put away for later.

I am quite positive the home directory is safe if there is no change of user. Consider also that including the executable will deprive us of our compression ability. Only the library will come with a 60mb size, the developer uses it together with a framework boom, he crosses 120mb. I think we should value compression above the unlikely event of multiple users on a machine.

**Comment by justvanrossum** [comment]
It's not that it's not safe, but it's simply not nice if a library saves files in a user's home directory without even asking. For my purposes, I may even prefer it to write into the package directory itself.

Regarding compression: a wheel is zip-compressed, so it shouldn't make a big difference if you compress before packaging it as a wheel. Also: a platform wheel would only contain the executable for the platform, whereas now your wheel contains the data for all three.

It's not an easy problem to solve for sure, especially given all the conflicting contraints!

**Comment by amoh-godwin** [comment]
Maybe we should have another build that comes with the executable. But I will still implement the home directory folder, again to be safe.

**Comment by amoh-godwin** [comment]
I have created a new repo [pyffmpeg-bin](https://github.com/deuteronomy-works/pyffmpeg-bin).
It implements the same namespace `pyffmpeg`, but you cannot install the two on one machine at the same time.

Install using
`pip install pyffmpeg-bin`

But import using
`from pyffmpeg import FFmpeg`
