### ISSUE TITLE
wrong output converting flv to mp4

### ISSUE THREAD

**Issue by sina-rostami** [deuteronomy-works/pyffmpeg#90]
it seems that the ffmpeg wrongs in converting some formats.
I write the code below to convert from `.flv` to `.mp4`:
```
from pyffmpeg import FFmpeg
ffmpeg = FFmpeg()
ffmpeg.convert('name.flv', 'name.mp4')
```
and it just maked an empty `name.mp4` file.
I also tried with options 
```
ffmpeg.options('-i name.flv  name.mp4')
```
also the same happened.

**Comment by amoh-godwin** [comment]
okay looking into it

**Comment by amoh-godwin** [comment]
Please check to make sure that the `name.flv` file is not empty.
If is not, then please attach a link to the file here so I can see what is going on.

**Comment by sina-rostami** [comment]
thanks anyway I found another way to do that.

**Comment by amoh-godwin** [comment]
Okay.
