### ISSUE TITLE
Cant import FFmpeg with python3 on CentOS 7.8

### ISSUE THREAD

**Issue by tgentry1986** [deuteronomy-works/pyffmpeg#91]
>>> from pyffmpeg import FFmpeg
>>> ff = FFmpeg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pyffmpeg/__init__.py", line 36, in __init__
    self._ffmpeg_file = Paths().load_ffmpeg_bin()
  File "/usr/local/lib/python3.6/site-packages/pyffmpeg/misc.py", line 47, in load_ffmpeg_bin
    from .static.bin.linux import linux
ImportError: cannot import name 'linux'

seems to work fine on Ubuntu

**Comment by amoh-godwin** [comment]
Sorry for the late reply.
This is due to the pyffmpeg platform tag manylinux2010 is not supported on CentOS 7.8. Sorry about that, I will update it to manylinux2014 which is supported

**Comment by tgentry1986** [comment]
Great, thank you! I'm about to deploy an app in an environment where centos is preferred over Ubuntu, so this is very helpful

**Comment by amoh-godwin** [comment]
@tgentry1986
A build have been made. Because it is released under alpha status until it is the tests have been updated

Please install using:
`pip install pyffmpeg==2.0.1a1`

**Comment by amoh-godwin** [comment]
@tgentry1986 I hope it works fine?

**Comment by tgentry1986** [comment]
i am afraid not ;-/

  Could not find a version that satisfies the requirement pyffmpeg==2.0.1a1 (from versions: 1.0.0-windows, 0.0.2, 1.1.1, 1.4, 1.4.1, 1.5, 1.6, 1.6.1, 1.7.0, 1.7.1, 1.7.2, 1.8a0, 1.8, 1.8.1a0, 1.8.1, 2.0a0, 2.0)
No matching distribution found for pyffmpeg==2.0.1a1

**Comment by amoh-godwin** [comment]
@tgentry1986 ok, please do

```pip install pyffmpeg``` and lets see

**Comment by tgentry1986** [comment]
It installed pyffmpeg-2.0.1 and the problem persists im afraid!

**Comment by amoh-godwin** [comment]
Please check 2 things for me
1) The name of the wheel that got installed (e.g. pyffmpeg-2.0.1-cp35.cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl)
also,
2) Run this python code, and tell me what it returns
```python
import platform
print(platform.system())
```

**Comment by tgentry1986** [comment]
Hi there,

Hows this?

[root@localhost ~]# locate *.whl
/root/.cache/pip/wheels/a3/2f/77/ad201dbd65121d969c7801da6d2c3d44db9a8bb91891757971/pyffmpeg-2.0.1-py2-none-any.whl

>>> import platform
>>> print(platform.system())
Linux

Cheers!

**Comment by amoh-godwin** [comment]
I do not have this file anywhere, its even a python2.

> 
> 
> /root/.cache/pip/wheels/a3/2f/77/ad201dbd65121d969c7801da6d2c3d44db9a8bb91891757971/pyffmpeg-2.0.1-py2-none-any.whl

Please manually download the wheel from the PyPI page for pyffmpeg. Click on the Download files tab and select the manylinux2014, I am sure that one will work on centos.

**Comment by qodzero** [comment]
Hi there, I'm getting this same error on my system:

Specs
============
Linux Version: Kubuntu 21.10
Pyffmpeg Version: 2.3
Python Version: 3.9

**Comment by amoh-godwin** [comment]
Sorry for the Delay @qodzero and @adhadse it will be fix shortly

**Comment by amoh-godwin** [comment]
@qodzero and @adhadse Please the issue has been resolved

**Comment by amoh-godwin** [comment]
Please, redownload the new version v2.3.0.1
